# Generated by Django 5.0.7 on 2024-09-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudForRegisterdEmployees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredworkers',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
