# Generated by Django 5.0.7 on 2024-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudForRegisterdEmployees', '0002_registeredworkers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredworkers',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
