# Generated by Django 5.1 on 2024-09-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudForRegisterdEmployees', '0003_alter_registeredworkers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredworkers',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
